apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shared-service
  name: redis-deploy
  labels:
    name: redis
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: myapp
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: myapp
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
     name: redis
     app: myapp
spec:
##clusterIP by default
  selector:
     name: redis
     app: myapp 
  ports:
  ##port of redis 
    - port: 6379
      targetPort: 6379

  